# Generated by Django 4.2.6 on 2023-10-16 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kirpykla', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barberreview',
            options={'verbose_name': 'barber review', 'verbose_name_plural': 'barber reviews'},
        ),
        migrations.AlterModelOptions(
            name='serviceorder',
            options={'verbose_name': 'service order', 'verbose_name_plural': 'service orders'},
        ),
    ]
